### ISSUE TITLE
Split uCC into its own repository

### ISSUE THREAD

**Issue by amedranogil** [universAAL/tools.runtime#4]
uCC is a full suite of tools, but they are meant for the user/deployer.
please vote 

- :+1:  for the split
- :-1:  for no split

**Comment by cstockloew** [comment]
I wouldn't do this right now. It first needs a heavy review and restructuring because it seems to be very much over-engineered. I guess that many of the modules can be combined/simplified..

It should be very clear what exactly the uCC should do, which functionality it should provide, and how it relates to the other tools. For example, I also played with the thought of combining log-monitor with uCC. Maybe the ace components and the sparql-tester should also be part of uCC. Should we keep the current UI framework (vaadin)? How does it work with the "new" Space concepts (and what about control bus via GW)?

I would first specify this and probably even (find someone to) work on the code before making a decision about repos.

**Comment by amedranogil** [comment]
This is precisely what I was thinking about, having a ucc repo, gives us the space to discuss all this independently of other tools; plus it gives us the time; as for right now full build of uAAL.pom fails due to a deprecated dependency (uaal.utilities) in an uCC module.

I think we should keep a clear vision for the uCC, as you state, but we also need a vision for the other tools. For example runtime tools could be used by developers to test their developments whereas uCC toolset should be used by (advanced) users and deployers. There is indeed an intersection between both; and there is nothing wrong in having modules imported from one repo to another, for example log monitor should be in tools.runtime, and for tools.ucc it should be imported directly or with a wrapper UI.

You make a great point about UI. The last thought I gave the uCC (uCC 2.0) I envisioned an eclipse application with many plugins, each for different functionalities, many for shared functionalities (such as  RDF instance editing). Maybe this vision is best for the tools.runtime where as a web interface is best suited for uCC. Maybe this is precisely the division we need: ucc.core, ucc.ui.eclipse, ucc.ui.web where each UI is configurable with the necesary plugins according to user (user, deployer, developer, each having respectively more functions in its uCC).

**Comment by cstockloew** [comment]
> as for right now full build of uAAL.pom fails due to a deprecated dependency (uaal.utilities) in an uCC module.

just fixed this.
In general, the modules should all work at any time no matter in which repo they are. If  something isn't working, fix it.

> There is indeed an intersection between both; 

IMHO this intersection is too big to make a clear separation. Also, I don't really see the benefit of it. Also, I don't think the separation should be done for different user groups. This reminds me of an old discussion about "AAL Space Profiles" where it was hardcoded which applications are able to run. I think this is part of the configuration, not of the source and its management.

**Comment by amedranogil** [comment]
essentially, we do not need a split, we need an upgrade:

1. move tools.ucc to top level
2. move other tools as modules of uCC Although tools.ace-server (which is a simple background service for automatic updating) may not fit this theory, but the other 3 would (but of course we need to have the uCC remodelling. plugin, and ui discussion).
